name = "risedle-router"
main = "dist/index.mjs"

compatibility_date = "2022-05-28"
compatibility_flags = []

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
