app = "risedle-graph-node"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DISABLE_BLOCK_INGESTOR = true
  ETHEREUM_POLLING_INTERVAL = 5000
  EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE = "synced"
  GRAPH_GRAPHQL_ERROR_RESULT_SIZE = 1000000
  GRAPH_GRAPHQL_WARN_RESULT_SIZE = 1000000
  GRAPH_NODE_ID = "risedle"
  GRAPH_SQL_STATEMENT_TIMEOUT = 5

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8000
  protocol = "tcp"
    [[services.tcp_checks]]
      grace_period = "60s"
      interval = "15s"
      restart_limit = 0
      timeout = "2s"

[[services]]
  internal_port = 8001
  protocol = "tcp"
    [[services.tcp_checks]]
      grace_period = "60s"
      interval = "15s"
      restart_limit = 0
      timeout = "2s"

[[services]]
  internal_port = 8020
  protocol = "tcp"
    [[services.tcp_checks]]
      grace_period = "60s"
      interval = "15s"
      restart_limit = 0
      timeout = "2s"
