name = "exchange-dev"
main = "entrypoint.server.ts"
compatibility_date = "2022-10-03"
compatibility_flags = ["streams_enable_constructors"]
tsconfig = "tsconfig.exchange.json"
workers_dev = true

[dev]
port = 3000

[env.production]
name = "exchange"

[env.staging]
name = "exchange-staging"

[site]
bucket = "./public"
# Only upload the following files:
# 1. JavaScript files to hydrate interactive components
# 2. CSS files that generated via esbuild
include = ["client.*.js", "global.css"]
