name = "exchange"
main = "entrypoint.server.ts"
compatibility_date = "2022-10-03"
compatibility_flags = ["streams_enable_constructors"]
tsconfig = "tsconfig.exchange.json"

#[site]
#bucket = "./public"
