name: monorepo

on:
  push:
    branches:
      - main
    paths-ignore:
      - "apps/interface/**"
      - ".github/workflows/risedle-interface.yml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "apps/interface/**"
      - ".github/workflows/risedle-interface.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "17.8.0"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Check format
        run: npm run check
      - name: Test
        run: npm run test
