name: bsc-prod

on:
  push:
    branches:
      - main
    paths:
      - "apps/interface/**"
      - ".github/workflows/risedle-interface-bsc.yml"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: bsc-prod
      url: https://bsc.risedle.com
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "17.8.0"
          cache: "npm"
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run:
          # prettier-ignore
          flyctl deploy --remote-only --app risedle-interface-bsc --config apps/interface/fly.toml
