name: "@risedle/chains"

on:
  push:
    branches:
      - main
    paths:
      - "packages/chains/**"

env:
  GIT_AUTHOR_NAME: risedle
  GIT_AUTHOR_EMAIL: github@risedle.com
  GIT_COMMITTER_NAME: risedle
  GIT_COMMITTER_EMAIL: github@risedle.com

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "17.8.0"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        working-directory: ./packages/chains
      - name: Test
        run: npm test
        working-directory: ./packages/chains
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        working-directory: ./packages/chains
